sources:
  - name: json_place_holder
    url: https://jsonplaceholder.typicode.com/posts
    table_destination_name: posts
    pagination:
      kind: limit_offset
      limit_param: _limit
      offset_param: _start
    retry:
      max_attempts: 3
      max_delay_secs: 5
      min_delay_secs: 1
  
  - name: json_place_holder2
    url: https://jsonplaceholder.typicode.com/posts
    table_destination_name: posts_2
    pagination:
      kind: limit_offset
      limit_param: _limit
      offset_param: _start
    retry:
      max_attempts: 3
      max_delay_secs: 5
      min_delay_secs: 1

targets:
  - name: postgres_sink
    type: postgres
    auth:
      username: postgres
      password: postgres
    host: localhost
    database: apitap